import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.module.css";
import Providers from "./Providers";
import Me from "@/components/auth/me.api";
import getSettings from "@/components/settings/settings.api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await Me().catch(() => null);
  const userId = user?._id ?? null;
  const settings = userId ? await getSettings(userId).catch(() => null) : null;
  const language = settings?.language;
  const htmlLang = language ?? "es";

  return (
    <html lang={htmlLang}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers initialLanguage={language} userId={userId}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
